create table if not exists users
(
    id      bigint generated by default as identity primary key,
    email   varchar(254) unique not null ,
    name    varchar(250) not null
);

create table if not exists categories
(
    id      bigint generated by default as identity primary key ,
    name    varchar(50) not null
);

create table if not exists compilations
(
    id      bigint generated by default as identity primary key ,
    pinned  boolean not null ,
    title   varchar(50) not null
);

create table if not exists locations
(
    id  bigint generated by default as identity  primary key ,
    lat float not null ,
    lon float not null
);

create table if not exists events
(
    id                  bigint generated by default as identity primary key ,
    annotation          varchar(2000) not null ,
    id_category         bigint references categories(id) on delete cascade ,
    created             timestamp not null ,
    description         varchar(7000) not null ,
    event_date          timestamp not null ,
    id_initiator        bigint references users(id) on delete cascade ,
    location            bigint references locations(id) on delete cascade ,
    paid                boolean not null ,
    participant_limit   int not null ,
    published_on        timestamp not null ,
    request_moderation  boolean not null ,
    state               varchar not null ,
    title               varchar(120) not null ,
    views               int not null
);

create table if not exists events_and_compilations
(
    id_event        bigint references events(id) on delete  cascade ,
    id_compilation  bigint references  compilations(id) on delete cascade
);

create table if not exists requests
(
    id              bigint generated by default as identity primary key ,
    created         timestamp not null ,
    id_event        bigint references events(id) on delete cascade ,
    id_requester    bigint references users(id) on delete cascade ,
    status          varchar not null
);