drop table if exists users, categories, compilations, events, events_and_compilations, locations, requests cascade;
create table if not exists users
(
    id    bigint generated by default as identity primary key,
    email varchar(254) not null,
    name  varchar(250) not null,

    constraint unique_user_email unique (email),
    constraint unique_user_name unique (name)
);

create table if not exists categories
(
    id   bigint generated by default as identity primary key,
    name varchar(50) not null,

    constraint unique_category_name unique (name)
);

create table if not exists compilations
(
    id     bigint generated by default as identity primary key,
    pinned boolean     not null,
    title  varchar(50) not null,

    constraint unique_title unique (title)
);

create table if not exists locations
(
    id  bigint generated by default as identity primary key,
    lat float not null,
    lon float not null,

    constraint unique_lat_lon unique (lat, lon)
);

create table if not exists events
(
    id                 bigint generated by default as identity primary key,
    annotation         varchar(2000)               not null,
    id_category        bigint references categories (id) on delete cascade,
    created            timestamp without time zone not null,
    description        varchar(7000)               not null,
    event_date         timestamp                   not null,
    id_initiator       bigint references users (id) on delete cascade,
    location           bigint references locations (id) on delete cascade,
    paid               boolean                     not null,
    participant_limit  int                         not null,
    published_on       timestamp without time zone default null,
    request_moderation boolean                     not null,
    state              varchar                     not null,
    title              varchar(120)                not null
);

create table if not exists events_and_compilations
(
    id_event       bigint references events (id) on delete cascade,
    id_compilation bigint references compilations (id) on delete cascade,

    primary key (id_compilation, id_event)
);

create table if not exists requests
(
    id           bigint generated by default as identity primary key,
    created      timestamp not null,
    id_event     bigint references events (id) on delete cascade,
    id_requester bigint references users (id) on delete cascade,
    status       varchar   not null,

    constraint unique_requester_id_for_one_event unique (id_event, id_requester)
);

create table if not exists comments
(
    id        bigint generated by default as identity primary key,
    text      varchar(1000) not null,
    id_author bigint references users (id) on delete cascade,
    id_event  bigint references events (id) on delete cascade,
    likes     int           not null,
    created   timestamp without time zone default null,
    status    varchar       not null
);