create table if not exists hits
(
    id        int generated by default as identity primary key,
    app       varchar(256)   not null,
    uri       varchar(512)   not null,
    ip        varchar(45)   not null,
    timestamp timestamp not null
);