create table if not exists hits
(
    id        int generated by default as identity primary key,
    app       varchar   not null,
    uri       varchar   not null,
    ip        varchar   not null,
    timestamp timestamp not null
);